Search in descriptions of courses if applicable (fixed formatting)
coursetable/coursetable pull request #1329
Opened 2023-09-19 03:42 UTC by GoldinGuy

2023-10-06 06:08 UTC, GoldinGuy commented on frontend/src/contexts/searchContext.tsx
> +	(numberFirstChar.toLowerCase() !== numberFirstChar.toUpperCase() &&
What is this referring to?

2023-10-06 06:09 UTC, Josh-Cena commented on frontend/src/contexts/searchContext.tsx
> +	(numberFirstChar.toLowerCase() !== numberFirstChar.toUpperCase() &&
The hack of `numberFirstChar.toLowerCase() !== numberFirstChar.toUpperCase()`. This doesn't work for anything other than ASCII, which is the case here, but there's a way that's both more concise and more robust.

2023-10-06 07:47 UTC, GoldinGuy commented on frontend/src/contexts/searchContext.tsx
> +	(numberFirstChar.toLowerCase() !== numberFirstChar.toUpperCase() &&
Ah. That is not a line of code I contributed, is there a reason it's holding up this PR?

2023-10-06 17:09 UTC, Josh-Cena approved these changes
I see—you changed the formatting so it wasn't as obvious. Re-ran formatting and now I see the change. This LGTM

2023-10-06 17:10 UTC, Josh-Cena requested changes
Actually, it cannot be shipped like this. Descriptions can contain arbitrary text and it will be very confusing when a lot more results show up while they do not look immediately related (because descriptions are only visible after you click on the entry). We need to hide this behind a checkbox.

2023-10-09 16:45 UTC, Josh-Cena commented
Hi @GoldinGuy thanks for the PR. There is https://github.com/coursetable/coursetable/pull/1353 also, and it seems much closer to the finish line (that one is implemented behind an option). As such I'll close this, but still thanks for the effort.

2023-10-09 16:45 UTC, closed without merging