feature: professor slider select (#1563)
coursetable/coursetable pull request #1564
Opened 2024-01-26 19:52 UTC by bearsyankees

feature #1563 to add a professor slider score

2024-01-26 20:33 UTC, Josh-Cena commented
@bearsyankees BTW, if you use "Fixes #1563" in your PR description it will auto-close the issue

2024-01-26 20:37 UTC, Josh-Cena requested changes
![image](https://github.com/coursetable/coursetable/assets/55398995/7f0b4e75-219b-4eab-a03e-1b1980ad4320)

There's a problem on tablet view (the reset button gets pushed to the next line). Maybe we should always put professor under advanced?

2024-01-26 21:22 UTC, bearsyankees commented
Yeah I think that's a good idea will do later may be offline a bit today and tom tho

2024-01-26 21:42 UTC, Josh-Cena commented
No hurries :)

2024-01-27 23:43 UTC, bearsyankees commented
> ![image](https://private-user-images.githubusercontent.com/55398995/300107570-7f0b4e75-219b-4eab-a03e-1b1980ad4320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTkxNDEsIm5iZiI6MTcwNjM5ODg0MSwicGF0aCI6Ii81NTM5ODk5NS8zMDAxMDc1NzAtN2YwYjRlNzUtMjE5Yi00ZWFiLWEwM2UtMWIxOTgwYWQ0MzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIzNDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTA0MDgzYzZmM2U0MTA5NzkwODZjNDRmZTFmODMwMDA2OTQyZjhlOWJjZmUzMGVlYTZmNmY0OTgxZGNhMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I98wjjjSARgYgolYfimdZm1wiUyMaAfn-PZqDAeppQc)
> 
> There's a problem on tablet view (the reset button gets pushed to the next line). Maybe we should always put professor under advanced?

always meaning even on desktop view?

2024-01-28 00:18 UTC, Josh-Cena commented
Yeah, but only hiding it on tablet is fine for me too

2024-01-28 03:21 UTC, Josh-Cena commented on frontend/src/components/Search/MobileSearchForm.tsx
> +              <div className={clsx('text-center', styles.filter_title)}>
```suggestion
              <div className={clsx('text-center', styles.filterTitle)}>
```

2024-01-28 03:24 UTC, Josh-Cena approved these changes

2024-01-28 03:29 UTC, merged