feat: worksheet split view on catalog page
coursetable/coursetable pull request #1624
Opened 2024-03-04 00:42 UTC by BradleyLewis08

## Pre-flight checklist

- [ ] I have searched for potential duplicate pull requests.
- [ ] **If this is a code change**: I have written unit tests and/or conducted manual tests to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes https://github.com/coursetable/coursetable/issues/1610) and the maintainers have approved on my working plan.

## Summary

This PR fixes/implements the following feature:

- Worksheet Split View

2024-03-04 01:54 UTC, bearsyankees commented
<img width="1440" alt="image" src="https://github.com/coursetable/coursetable/assets/46074070/97569209-79eb-4719-bf5d-610794457d68">
Can we make the worksheet preview bigger so i can see the full thing? this looks epic so far great stuff

2024-03-04 02:32 UTC, bearsyankees requested changes
(see above)

2024-03-04 02:56 UTC, Josh-Cena commented on frontend/src/pages/OverlayComponent.tsx
> +import React, { useEffect } from 'react';
Move these files to `components`; `pages` are for the route components

2024-03-11 02:41 UTC, Josh-Cena commented
Hi @BradleyLewis08 @bearsyankees I've made some edits.

- Most notably: I'm now using `WorksheetCalendar` instead of `Worksheet`. This means we don't need to hook into `worksheetView`.
  - Why? Because otherwise when you navigate away from this page, the worksheet view stays as `overlay`, and we don't know which view to restore it too!
  - This is up for discussion: will people ever want to see the worksheet in "list" view?
  - Will they want to see a list of courses they've added to the worksheet, like the right sidebar on the worksheet page?
  - My answer is "no", and it's too hard to design it otherwise.
- I've added mobile support (and support in grid view).
- The calendar bottom no longer overflows the screen.
- Little CSS improvements.
- Moved some files

LMK if they look good

2024-03-11 02:41 UTC, Josh-Cena commented
For a stable branch preview, please use the following URL: https://ewis-worksheet-split-view.preview.coursetable.com/catalog

2024-03-11 02:43 UTC, Josh-Cena approved these changes
Rubber stamping: effect looks good to me now

2024-03-14 00:26 UTC, neilsong commented
Two things before it LGTM:

1. Let's make the fullscreen icon padded from the top border
<img width="188" alt="image" src="https://github.com/coursetable/coursetable/assets/67600593/cd2a272d-8999-49da-ad4d-21bf0389d053">

2. Let's persist the state of the split view (shown or hidden) after navigating to and from a different page

Other than that - good stuff looks awesome

2024-03-16 21:54 UTC, Josh-Cena commented
@neilsong Please take another look

2024-03-16 22:09 UTC, neilsong commented
LGTM thank you for your commits :pray:

2024-03-16 22:09 UTC, neilsong approved these changes

2024-03-17 05:25 UTC, bearsyankees commented
@neilsong @Josh-Cena only 1 thing from me -- do we still want it on public view (as it is right now)? I am not entirely opposed as it shows what features they could have if they sign in, but also is not useful at all as of now without public worksheet

2024-03-17 09:11 UTC, Josh-Cena commented
I think this one is fine. The idea is to eventually have as little branching logic as possible except for things unauthorized users cannot see.

2024-03-17 16:23 UTC, bearsyankees commented
> I think this one is fine. The idea is to eventually have as little branching logic as possible except for things unauthorized users cannot see.

OK LGTM then

2024-03-17 16:23 UTC, bearsyankees approved these changes

2024-03-17 17:26 UTC, merged